language: java

sudo: false

jdk:
 - oraclejdk8 
 - oraclejdk7

branches:
  only:
    - master

after_success:
  - echo "<settings><servers><server><id>nexus</id><username>\${env.NEXUS_USER}</username><password>\${env.NEXUS_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn clean deploy -Dmaven.test.skip=true --settings ~/settings.xml
