language: java

jdk:
 - oraclejdk8 
 - oraclejdk7
addons:
  postgresql: "9.3"

services: postgresql

env:
  - DB=postgresql

before_install:
 - psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; 

branches:
  only:
    - master

after_success:
  - echo "<settings><servers><server><id>nexus</id><username>\${env.NEXUS_USER}</username><password>\${env.NEXUS_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn clean deploy -Dmaven.test.skip=true --settings ~/settings.xml
