language: java

jdk:
 - oraclejdk8 
 - oraclejdk7
 
addons:
 -postgresql: "9.3"

services: postgresql

before_script:
 - psql -c "DROP DATABASE IF EXISTS sincap_teste;" -U postgres
 - psql -c "CREATE DATABASE sincap_teste;" -U postgres
 - psql -U postgres -d sincap_teste -f src/main/resources/sincapBackup.sql
 
branches:
  only:
    - master

after_success:
  - mvn sonar:sonar
  - echo "<settings><servers><server><id>nexus</id><username>\${env.NEXUS_USER}</username><password>\${env.NEXUS_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn clean deploy -Dmaven.test.skip=true --settings ~/settings.xml

notifications:
  slack: leds:Bdewxwg54FgRsFjl9zN5iRFI
